name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger this action only on the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (required for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub using the secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t Pteus91/go-gin-games-api:latest .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push Pteus91/go-gin-games-api:latest
